version: '3.8'

services:
  weather-api:
    build: .
    ports:
      - '8080:8080'
    environment:
      - 3RD_PARTY_API_KEY=FBNDSCDTK7D768WNDYEPSGVNR
      - REDIS_CONN_HOST=redis
      - REDIS_CONN_PORT=6379
    networks:
      - weather-network

  redis:
    image: redis:alpine
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - '6379:6379'
    networks:
      - weather-network

networks:
  weather-network: